[package]
name = "rust-closures"
version = "0.1.0"
authors = ["王兴彬_Binboy <binboy@live.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
